name: WatchDog Update Monitor

on:
  schedule:
    - cron: '0 * * * *'
  
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Warning fix: Node version 24 kar diya

      - name: Install dependencies
        run: npm install

      # Naya Step: Puppeteer ke liye Chrome manually install karna (Error fix)
      - name: Install Puppeteer Chrome
        run: npx puppeteer browsers install chrome

      - name: Run the script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: node index.js